#!/usr/bin/env ruby

HOME_DIR = File.expand_path(File.dirname(__FILE__) + '/../')
WORK_DIR = Dir.pwd
PROJECTS_DIR = HOME_DIR + '/etc/projects/'

require 'fileutils'
require 'optparse'
require 'json'
require HOME_DIR + '/lib/config'

options = load_config(HOME_DIR + '/etc/tim.conf');

optparse = OptionParser.new do|opts|
    opts.banner = "Usage: tim projects command [options]"
    opts.on( '-h', '--help', 'Display this screen' ) do
        puts opts
        exit
    end
end

optparse.parse!

def get_list_of_projects(options)
  repo_paths = Dir.glob(File.expand_path(options["projects_dir"]) + "/*/.git").map{ |dir| File.expand_path("..", dir) }
  repo_paths.concat Dir.glob(File.expand_path(options["projects_dir"]) + "/*/.svn").map{ |dir| File.expand_path("..", dir) }
  repo_paths.select!{ |path| File.exist? path + "/.tim" }
  repo_paths.each do |repo|
    puts ' * ' + File.basename(repo)
  end
end

command = ARGV.shift
case command
    when 'list'
        puts "Available projects:"
        get_list_of_projects(options)
    else
        puts "Unknown command..."
        exit 1
end
